var res = {
    // 公共声音
    Right_audio: 'common/audios/right.mp3',
    Wrong_audio: 'common/audios/wrong.mp3',
    Win_audio: 'common/audios/celebration.mp3',
    Star_audio: 'common/audios/star.mp3',
    Button_audio: 'common/audios/button.mp3',

    // 公共图片
    // bar_plist: 'common/imgs/bar.plist',
    // color_bar: 'common/imgs/color_bar.png',
    Back: 'common/imgs/back.png',
    BlackStar: 'common/imgs/shape.png',
    FlyStar: 'common/imgs/flay-star.png',
    LightStar: 'common/imgs/light-star.png',
    ResultBg: 'common/imgs/result-image-bg.png',
    hand: 'common/imgs/hand.png',
    handclick: 'common/imgs/handclick.png',
    sound: 'common/imgs/sound_button.png',
    button_green: 'common/imgs/button_green.png',
    button_next: 'common/imgs/button_next.png',
    star_finish: 'common/imgs/star_finish.png',//source图片arrow: 'source/arrow.png',bg01: 'source/bg01.png',bg02: 'source/bg02.png',blackbaord: 'source/blackbaord.png',box: 'source/box.png',chelun1: 'source/chelun1.png',chelun2: 'source/chelun2.png',chukou: 'source/chukou.png',chumiguan: 'source/chumiguan.png',dianshiji: 'source/dianshiji.png',end: 'source/end.png',feiliao1: 'source/feiliao1.png',feiliao2: 'source/feiliao2.png',fenzhi_bmh: 'source/fenzhi_bmh.png',fenzhi_bmh_gl: 'source/fenzhi_bmh_gl.png',fenzhi_mantou: 'source/fenzhi_mantou.png',fenzhi_mantou_gl: 'source/fenzhi_mantou_gl.png',fenzhi_mb: 'source/fenzhi_mb.png',fenzhi_mb_gl: 'source/fenzhi_mb_gl.png',fenzhi_mibing: 'source/fenzhi_mibing.png',fenzhi_mibing_gl: 'source/fenzhi_mibing_gl.png',fenzhi_mifan: 'source/fenzhi_mifan.png',fenzhi_mifan_gl: 'source/fenzhi_mifan_gl.png',fenzhi_shutiao: 'source/fenzhi_shutiao.png',fenzhi_shutiao_gl: 'source/fenzhi_shutiao_gl.png',fenzhi_tudouni: 'source/fenzhi_tudouni.png',fenzhi_tudouni_gl: 'source/fenzhi_tudouni_gl.png',fenzhi_yumib: 'source/fenzhi_yumib.png',fenzhi_yumib_gl: 'source/fenzhi_yumib_gl.png',liangshi: 'source/liangshi.png',liangshi1: 'source/liangshi1.png',liangshi2: 'source/liangshi2.png',liangshi3: 'source/liangshi3.png',liangshihe: 'source/liangshihe.png',luofeiliao: 'source/luofeiliao.png',luoliangshi: 'source/luoliangshi.png',miya1: 'source/miya1.png',miya2: 'source/miya2.png',miya3: 'source/miya3.png',miya4: 'source/miya4.png',miyawen1: 'source/miyawen1.png',miyawen2: 'source/miyawen2.png',nf1: 'source/nf1.png',nf2: 'source/nf2.png',nf3: 'source/nf3.png',nf4: 'source/nf4.png',nf5: 'source/nf5.png',nf6: 'source/nf6.png',nf7: 'source/nf7.png',nf8: 'source/nf8.png',nff: 'source/nff.png',padong1: 'source/padong1.png',padong2: 'source/padong2.png',qipao: 'source/qipao.png',shachongji1: 'source/shachongji1.png',shachongji2: 'source/shachongji2.png',shougegun: 'source/shougegun.png',shuidaosg1: 'source/shuidaosg1.png',shuidaosg2: 'source/shuidaosg2.png',shuidaosg3: 'source/shuidaosg3.png',shuidaoyang: 'source/shuidaoyang.png',star: 'source/star.png',talk1: 'source/talk1.png',talk_tu1: 'source/talk_tu1.png',talk_tu2: 'source/talk_tu2.png',talk_tu3: 'source/talk_tu3.png',talk_tu4: 'source/talk_tu4.png',tu01: 'source/tu01.png',tu02: 'source/tu02.png',tu03: 'source/tu03.png',tu04: 'source/tu04.png',tuolaji: 'source/tuolaji.png',tv_shadow: 'source/tv_shadow.png',wenzi1: 'source/wenzi1.png',wenzi2: 'source/wenzi2.png',wenzi2_1: 'source/wenzi2_1.png',wenzi2_2: 'source/wenzi2_2.png',wenzi3: 'source/wenzi3.png',yan1: 'source/yan1.png',yan2: 'source/yan2.png',yan3: 'source/yan3.png',zd1: 'source/zd1.png',zd2: 'source/zd2.png',zd3: 'source/zd3.png',zd4: 'source/zd4.png',zd5: 'source/zd5.png',zd6: 'source/zd6.png',zd7: 'source/zd7.png',zd8: 'source/zd8.png',粮食从哪里来01: 'source/粮食从哪里来01.png',//source声音s10_sound: 'audio/s10.mp3',s11_sound: 'audio/s11.mp3',s2_sound: 'audio/s2.mp3',s3_sound: 'audio/s3.mp3',s4_sound: 'audio/s4.mp3',s5_sound: 'audio/s5.mp3',s6_sound: 'audio/s6.mp3',s7_sound: 'audio/s7.mp3',s8_sound: 'audio/s8.mp3',s9_sound: 'audio/s9.mp3'}/* 预加载资源*/
  var g_resources = []
  for (var i in res) {
    g_resources.push(res[i])
  }