var res = {
    // 公共声音
    Right_audio: 'common/audios/right.mp3',
    Wrong_audio: 'common/audios/wrong.mp3',
    Win_audio: 'common/audios/celebration.mp3',
    Star_audio: 'common/audios/star.mp3',
    Button_audio: 'common/audios/button.mp3',

    // 公共图片
    // bar_plist: 'common/imgs/bar.plist',
    // color_bar: 'common/imgs/color_bar.png',
    Back: 'common/imgs/back.png',
    BlackStar: 'common/imgs/shape.png',
    FlyStar: 'common/imgs/flay-star.png',
    LightStar: 'common/imgs/light-star.png',
    ResultBg: 'common/imgs/result-image-bg.png',
    hand: 'common/imgs/hand.png',
    handclick: 'common/imgs/handclick.png',
    sound: 'common/imgs/sound_button.png',
    button_green: 'common/imgs/button_green.png',
    button_next: 'common/imgs/button_next.png',
    star_finish: 'common/imgs/star_finish.png',//source图片aimi1: 'source/aimi1.png',aimi2: 'source/aimi2.png',anna1: 'source/anna1.png',anna2: 'source/anna2.png',apple1: 'source/apple1.png',apple10: 'source/apple10.png',apple101: 'source/apple101.png',apple10ge: 'source/apple10ge.png',apple2: 'source/apple2.png',banana1: 'source/banana1.png',banana2: 'source/banana2.png',banana8: 'source/banana8.png',banana81: 'source/banana81.png',banana8ge: 'source/banana8ge.png',bg: 'source/bg.png',bg1: 'source/bg1.png',bg2: 'source/bg2.png',blackboard1: 'source/blackboard1.png',blackboard2: 'source/blackboard2.png',box: 'source/box.png',chengzi1: 'source/chengzi1.png',chengzi2: 'source/chengzi2.png',chengzi7ge: 'source/chengzi7ge.png',jieni1: 'source/jieni1.png',jieni2: 'source/jieni2.png',lianxian1: 'source/lianxian1.png',lianxian2: 'source/lianxian2.png',lianxian3: 'source/lianxian3.png',lianxian4: 'source/lianxian4.png',lianxian5: 'source/lianxian5.png',mango1: 'source/mango1.png',mango2: 'source/mango2.png',mango9: 'source/mango9.png',mango91: 'source/mango91.png',mango9ge: 'source/mango9ge.png',miya1: 'source/miya1.png',miya2: 'source/miya2.png',miya3: 'source/miya3.png',miya4: 'source/miya4.png',orange7: 'source/orange7.png',orange71: 'source/orange71.png',peach1: 'source/peach1.png',peach2: 'source/peach2.png',peach6: 'source/peach6.png',peach61: 'source/peach61.png',qipao: 'source/qipao.png',shadow: 'source/shadow.png',shu1: 'source/shu1.png',shu10: 'source/shu10.png',shu2: 'source/shu2.png',shu3: 'source/shu3.png',shu4: 'source/shu4.png',shu5: 'source/shu5.png',shu6: 'source/shu6.png',shu7: 'source/shu7.png',shu8: 'source/shu8.png',shu9: 'source/shu9.png',talk11: 'source/talk11.png',talk12: 'source/talk12.png',talk2: 'source/talk2.png',talk3: 'source/talk3.png',talk4: 'source/talk4.png',talk5: 'source/talk5.png',talk6: 'source/talk6.png',taozi6ge: 'source/taozi6ge.png',title: 'source/title.png',wenzi: 'source/wenzi.png',whiteboard: 'source/whiteboard.png',zhuti: 'source/zhuti.png',//source声音niaojiao_sound: 'audio/niaojiao.mp3',s11_sound: 'audio/s11.mp3',s12_sound: 'audio/s12.mp3',s13_sound: 'audio/s13.mp3',s14_sound: 'audio/s14.mp3',s15_sound: 'audio/s15.mp3',s16_sound: 'audio/s16.mp3',s2_sound: 'audio/s2.mp3',s3_sound: 'audio/s3.mp3',s5_sound: 'audio/s5.mp3',s6_sound: 'audio/s6.mp3',s8_sound: 'audio/s8.mp3',s9_sound: 'audio/s9.mp3'}/* 预加载资源*/
  var g_resources = []
  for (var i in res) {
    g_resources.push(res[i])
  }